In [4]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [5]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [7]:
one_hot("amazing restaurant",50)

[26, 46]

In [8]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[16, 5], [10, 24], [26, 7], [24, 22, 24], [15, 23, 2], [27, 5], [20, 23, 26], [26, 15], [26, 14], [14, 20]]


In [10]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[16  5  0]
 [10 24  0]
 [26  7  0]
 [24 22 24]
 [15 23  2]
 [27  5  0]
 [20 23 26]
 [26 15  0]
 [26 14  0]
 [14 20  0]]


In [12]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [13]:
X = padded_reviews
y = sentiment

In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________
None


In [17]:
model.fit(X, y, epochs=100, verbose=0)

In [18]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 22ms/step - loss: 0.5118 - accuracy: 1.0000


1.0

In [19]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [20]:
weights[15]

array([0.19063786, 0.15482076, 0.13385345, 0.14866628], dtype=float32)

In [21]:
weights[5]

array([ 0.03096088, -0.08176231, -0.09718509, -0.0737474 ], dtype=float32)

In [22]:
weights[16]

array([0.16387548, 0.22707158, 0.07749712, 0.06498955], dtype=float32)